openapi: "3.0.1"
info:
  title: "Serverless Query API"
  version: "0.0.1"
security: []
paths:
  /query:
    post:
      description: Triggers lambda function to run query
      security: []
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: # note that shorthand substitution is not supported in open api, so we use long form substitution
          Fn::Sub:
            - 'arn:aws:apigateway:${AWSRegion}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations'
            - AWSRegion:
                  Ref: AWS::Region
              FunctionArn:
                  Fn::GetAtt: [RunQueryFunction, Arn]
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: Query Results
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      data:
                        type: string
