AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: serverless query SAM template

Parameters:
  ApiStage:
    Type: String
    Description: Enter the name of the stage to deploy. Ex. dev, v1
    Default: "dev"

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  QueryApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "Query API"
      Description: !Ref AWS::StackName
      StageName: !Ref ApiStage
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./openapi.yaml # All API endpoints should be added to the open api spec

  RunQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/run_query/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /query
            Method: POST
            RestApiId: !Ref QueryApi
      Environment:
        Variables:
          DATA_BUCKET: !Ref QueryDataBucket

  QueryDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - '-'
        - - 'query-data'
          - !Select [2, !Split ['/', !Ref AWS::StackId]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter

Outputs:
  QueryApiBaseUri:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${QueryApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiStage}"
  QueryDataBucket:
    Description: "Query Data bucket"
    Value: !Ref QueryDataBucket
