AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: serverless query SAM template

Globals:
  Function:
    Timeout: 120
    MemorySize: 1024

Resources:
  RunQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/run_query/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          DATA_BUCKET_NAME: !Ref QueryDataBucket
          HOME: /tmp
      Policies:
        - Statement:
          - Sid: ReadFromQueryDataBucket
            Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub "${QueryDataBucket.Arn}/*"

  QueryDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - '-'
        - - 'query-data'
          - !Select [2, !Split ['/', !Ref AWS::StackId]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter

Outputs:
  QueryApiBaseUri:
    Description: "Run query lambda"
    Value: !Ref RunQueryFunction
  QueryDataBucket:
    Description: "Query Data bucket"
    Value: !Ref QueryDataBucket
